# =============================================================
#  terraform/iam_cert.tf
#
#  Reads the mkcert self-signed certificate from your local
#  certs/ folder and uploads it to the AWS IAM certificate
#  store automatically during  terraform apply.
#
#  Prerequisites (run once on your machine before terraform apply):
#    1. mkcert -install
#    2. Run scripts/generate-certs-mkcert.sh  (or the .ps1 version)
#       → creates  certs/server.crt  and  certs/server.key
#    3. Find your mkcert CA root path:
#         PowerShell:  mkcert -CAROOT
#       Paste that path into terraform.tfvars as  cert_chain_path
# =============================================================

resource "aws_iam_server_certificate" "self_signed" {
  # Name includes a short hash of the cert content so it changes
  # automatically when you regenerate the cert with mkcert.
  # This lets Terraform create the new cert before deleting the old
  # one (create_before_destroy), which keeps the ALB serving HTTPS
  # with zero downtime during cert rotation.
  name = "${var.project_name}-selfsigned-${substr(sha256(file("${path.module}/../certs/server.crt")), 0, 8)}"

  # The server certificate — certs/server.crt generated by mkcert
  certificate_body = file("${path.module}/../certs/server.crt")

  # The private key — certs/server.key generated by mkcert
  # Terraform marks this sensitive; it never appears in plan output.
  private_key = file("${path.module}/../certs/server.key")

  # The mkcert local CA root — this is what makes the cert chain valid.
  # Without this, the ALB will reject the certificate upload.
  # Set cert_chain_path in terraform.tfvars (see variables.tf for instructions).
  certificate_chain = file(var.cert_chain_path)

  lifecycle {
    # Create the new cert first, update the ALB listener, then delete
    # the old cert. Safe for cert rotation — no HTTPS outage.
    create_before_destroy = true
  }
}
